server:
  # 服务http端口
  port: 8090
  # tomcat配置
  tomcat:
    # 最大线程数
    max-threads: 6
    # 最小线程数
    min-spare-threads: 3
    # 队列长度
    accept-count: 10
    # 最大链接数
    max-connections: 1000
    #链接建立超时时间
  connection-timeout: 10000
